language: python
before_install:
  - >
    [ -f ffmpeg-release/ffmpeg ] || (
        curl -O https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz &&
        mkdir -p ffmpeg-release &&
        tar Jxf ffmpeg-release-amd64-static.tar.xz --strip-components=1 -C ffmpeg-release
    )
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      dist: xenial  # required for Python >= 3.7
      env: TOX_ENV=py37
    - python: pypy
      env: TOX_ENV=pypy
install:
  - pip install tox
script:
  - export PATH=$(readlink -f ffmpeg-release):$PATH
  - tox -e $TOX_ENV
cache:
  directories:
    - .tox
    - ffmpeg-release
